version: '3'
services:
  qmk-docker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./app/qmk_firmware:/root/qmk_firmware
    network_mode: bridge
    ports:
      - 80:80
